name: Deploy

on: [push]

jobs:
  pack-unitypackage:
    runs-on: ubuntu-20.04
    name: Pack Unity Package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Find all meta files
        run: |
          echo "Assets/Materials.meta" > metaList
          echo "Assets/PhysicsMaterials.meta" > metaList
          echo "Assets/Prefabs.meta" > metaList
          echo "Assets/Scenes.meta" > metaList
          echo "Assets/Scripts.meta" > metaList
          find Assets/Materials -name \*.meta >> metaList
          find Assets/PhysicsMaterials -name \*.meta >> metaList
          find Assets/Prefabs -name \*.meta >> metaList
          find Assets/Scenes -name \*.meta >> metaList
          find Assets/Scripts -name \*.meta >> metaList
      - name: Make directory for our unity package
        run: mkdir a
      - name: Create Unity Package
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'a/hellounity.unitypackage'
          include-files: metaList
      - name: Upload package
        uses: actions/upload-artifact@v1
        with:
          name: a
          path: ./a

  release:
    runs-on: ubuntu-20.04
    needs: pack-unitypackage
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine version
        run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: 1.0.0
          name: Release 1.0.0
          body: 1.0.0
          makeLatest: true
      - name: Download unity package
        uses: actions/download-artifact@v1
        with:
          name: a
          path: ./a
      - name: Upload unity package to release
        uses: Fhwang0926/upload-release-asset@v1.1.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_name: a/hellounity.unitypackage # path + filename



